import { AnalyticsEventMap } from 'shared/analytics/types/v3/event/analyticsEventMap';

export enum AnalyticsEventCategories {
	App = 'App',
	Browse = 'Browse',
	Cta = 'Cta',
	User = 'User',
	Item = 'Item',
	Menu = 'Menu',
	Subscription = 'Subscription',
	Playback = 'Playback',
	Error = 'Error'
}

export const AnalyticsEventTypeMap: { [_ in keyof AnalyticsEventMap]: AnalyticsEventCategories } = {
	'App Started': AnalyticsEventCategories.App,
	'App Ready': AnalyticsEventCategories.App,
	'App Closed': AnalyticsEventCategories.App,
	'App Offline': AnalyticsEventCategories.App,
	'App Online': AnalyticsEventCategories.App,
	'Banner Shown': AnalyticsEventCategories.Browse,
	'Banner Clicked': AnalyticsEventCategories.Browse,
	'Banner Closed': AnalyticsEventCategories.Browse,
	'Page Viewed': AnalyticsEventCategories.Browse,
	'Item Detail Page Viewed': AnalyticsEventCategories.Browse,
	'My List Page Viewed': AnalyticsEventCategories.Browse,
	'List Page Viewed': AnalyticsEventCategories.Browse,
	'Watch Page Viewed': AnalyticsEventCategories.Browse,
	'Filter Request': AnalyticsEventCategories.Browse,
	'CW Menu Undo Remove Multiple': AnalyticsEventCategories.Browse,
	'CW Page Edit': AnalyticsEventCategories.Browse,
	'CW Page Select All': AnalyticsEventCategories.Browse,
	'CW Page Deselect All': AnalyticsEventCategories.Browse,
	'CW Page Remove Selected': AnalyticsEventCategories.Browse,
	'Autofill Search Item Clicked': AnalyticsEventCategories.Browse,
	Searched: AnalyticsEventCategories.Browse,
	'Entry Viewed': AnalyticsEventCategories.Browse,
	'Entry Interacted': AnalyticsEventCategories.Browse,
	'Rail Header Clicked': AnalyticsEventCategories.Browse,

	'Menu Clicked': AnalyticsEventCategories.Menu,

	'Resource Error': AnalyticsEventCategories.Error,
	'Client Error': AnalyticsEventCategories.Error,
	'Server Error': AnalyticsEventCategories.Error,
	'System Error': AnalyticsEventCategories.Error,
	'Unknown Error': AnalyticsEventCategories.Error,

	'Item Viewed': AnalyticsEventCategories.Item,
	'Item Clicked': AnalyticsEventCategories.Item,
	'Item Clicked To Watch': AnalyticsEventCategories.Item,
	'Item User Preferences Clicked': AnalyticsEventCategories.Item,
	'Item Watched': AnalyticsEventCategories.Item,
	'Item Detail Viewed': AnalyticsEventCategories.Item,
	'Item Focused': AnalyticsEventCategories.Item,
	'Item Actioned': AnalyticsEventCategories.Item,
	'Item Bookmark Add Clicked': AnalyticsEventCategories.Item,
	'Item Bookmark Remove Clicked': AnalyticsEventCategories.Item,
	'Item Bookmarked': AnalyticsEventCategories.Item,
	'Item Rated': AnalyticsEventCategories.Item,
	'Item Offered': AnalyticsEventCategories.Item,
	'Item Rented': AnalyticsEventCategories.Item,
	'Item Owned': AnalyticsEventCategories.Item,
	'Item Subscribe Clicked': AnalyticsEventCategories.Item,
	'Item Watch Program Trailer': AnalyticsEventCategories.Item,
	'Item Program Tag Clicked': AnalyticsEventCategories.Item,
	'Item Program Synopsis Clicked': AnalyticsEventCategories.Item,
	'Item IDP Link Clicked': AnalyticsEventCategories.Item,
	'Item Info Link Clicked': AnalyticsEventCategories.Item,
	'Item Info Icon Clicked': AnalyticsEventCategories.Item,
	'Item Set Reminder': AnalyticsEventCategories.Item,
	'CW Menu Clicked': AnalyticsEventCategories.Item,
	'CW Menu Remove CW': AnalyticsEventCategories.Item,
	'CW Menu Undo Remove': AnalyticsEventCategories.Item,
	'CW Menu View Info': AnalyticsEventCategories.Item,
	'CW Page Select Single Remove': AnalyticsEventCategories.Item,

	'CTA Clicked': AnalyticsEventCategories.Cta,
	'CTA Social Share Clicked': AnalyticsEventCategories.Cta,

	'Subscribe Page': AnalyticsEventCategories.Subscription,
	'Subscription View Plan': AnalyticsEventCategories.Subscription,
	'Subscribe Select Plans': AnalyticsEventCategories.Subscription,
	'Subscribe Apply Promo': AnalyticsEventCategories.Subscription,
	'Subscribe Proceed To Payment': AnalyticsEventCategories.Subscription,
	'Subscribe Proceed To Pay': AnalyticsEventCategories.Subscription,
	'Subscribe Confirm And Proceed': AnalyticsEventCategories.Subscription,
	'Subscription Failure': AnalyticsEventCategories.Subscription,
	'Subscription Success': AnalyticsEventCategories.Subscription,

	'User Profile Selected': AnalyticsEventCategories.User,
	'User Actioned': AnalyticsEventCategories.User,
	'User Registered': AnalyticsEventCategories.User,
	'User Registering': AnalyticsEventCategories.User,
	'User Identified': AnalyticsEventCategories.User,
	'User Signed Out': AnalyticsEventCategories.User,
	'User Signed In': AnalyticsEventCategories.User,

	'Video Initialized': AnalyticsEventCategories.Playback,
	'Video First Playing': AnalyticsEventCategories.Playback,
	'Video Requested': AnalyticsEventCategories.Playback,
	'Video Playing': AnalyticsEventCategories.Playback,
	'Video Progressed': AnalyticsEventCategories.Playback,
	'Video Completed': AnalyticsEventCategories.Playback,
	'Video Error': AnalyticsEventCategories.Playback,
	'Video Exit': AnalyticsEventCategories.Playback,
	'Video Actioned': AnalyticsEventCategories.Playback,
	'Video Buffering': AnalyticsEventCategories.Playback,
	'Video Actuate Pause': AnalyticsEventCategories.Playback,
	'Video Paused': AnalyticsEventCategories.Playback,
	'Video Actuate Play': AnalyticsEventCategories.Playback,
	'Video Resumed': AnalyticsEventCategories.Playback,
	'Video Seeked': AnalyticsEventCategories.Playback,
	'Video Restarted': AnalyticsEventCategories.Playback,
	'Video Chainplayed': AnalyticsEventCategories.Playback,
	'Video Linear Program Updated': AnalyticsEventCategories.Playback,
	'Video Ad Loaded': AnalyticsEventCategories.Playback,
	'Video Ad Started': AnalyticsEventCategories.Playback,
	'Video Ad Progress': AnalyticsEventCategories.Playback,
	'Video Ad Quartile': AnalyticsEventCategories.Playback,
	'Video Ad Paused': AnalyticsEventCategories.Playback,
	'Video Ad Completed': AnalyticsEventCategories.Playback,
	'Video Ad Skipped': AnalyticsEventCategories.Playback,
	'Video Ad Volume Changed': AnalyticsEventCategories.Playback,
	'Video Can Play': AnalyticsEventCategories.Playback,
	'Video Item Clicked': AnalyticsEventCategories.Playback,
	'Video Select Audio': AnalyticsEventCategories.Playback,
	'Video Select Quality': AnalyticsEventCategories.Playback,
	'Video Select Subtitle': AnalyticsEventCategories.Playback,
	'Video Watch Completed': AnalyticsEventCategories.Playback,
	'Video Start Over Clicked': AnalyticsEventCategories.Playback,

	'User Personalisation Preferences Genres': AnalyticsEventCategories.User,
	'User Personalisation Preferences Assets': AnalyticsEventCategories.User,

	'Generic Analytics Event': AnalyticsEventCategories.User
};
