// ISL ERROR CODES

// Commerce errors
import { VideoErrorCode } from 'shared/util/VideoError';

export const COMMERCE_ERROR = 2201;
export const PAYMENT_REJECTED = 2202;
export const CARD_EXPIRED = 2203;
export const INVALID_CARD_DETAILS = 2204;
export const INSUFFICIENT_FUNDS = 2205;
export const INVALID_ACCOUNT_TYPE = 2206;
export const CVV_VALIDATION_ERROR = 2207;
export const PIN_TRIES_EXCEEDED = 2208;
export const AUTHENTICATION_ERROR = 2209;
export const PROFILE_LOCKED_OUT = 333;

// Authorization errors
export const AUTHORIZATION_UNKNOWN = 0;
export const AUTHORIZATION_ACCESS_TOKEN_EXPIRED = 1;
export const AUTHORIZATION_ACCOUNT_LOCKED = 2;
export const AUTHORIZATION_ACCOUNT_DISABLED = 3;
export const AUTHORIZATION_INVALID_ACCESS_TOKEN_TYPE = 4;
export const AUTHORIZATION_INVALID_ACCESS_TOKEN_SCOPE = 5;
export const AUTHORIZATION_ACCESS_TO_RESOURCE_DENIED = 6;
export const AUTHORIZATION_ACCESS_TO_CONTENT_DENIED = 7;
export const AUTHORIZATION_ACCOUNT_CONFIRMATION_PENDING = 8;
export const AUTHORIZATION_PROFILE_LOCKED = 9;
export const AUTHORIZATION_PLOFILE_DISABLED = 10;
export const AUTHORIZATION_ACCOUNT_NOT_EXIST = 11;

export const VALID_ENTITLEMENT_ALREADY_EXISTS_FOR_ITEM = 700;

export const PLAYBACK_AUTH_NO_ENTITLEMENT = 3001;
export const PLAYBACK_AUTH_LOCATION_RESTRICTION = 3002;
export const PLAYBACK_AUTH_STREAM_COUNT_EXCEEDED = 3002;
export const PLAYBACK_AUTH_PLAY_COUNT_EXCEEDED = 3004;
export const PLAYBACK_AUTH_DOWNLOAD_COUNT_EXCEEDED = 3005;
export const PLAYBACK_AUTH_DEVICE_ERROR = 3006;
export const PLAYBACK_ADAPTER_LOAD_FAILED = 3022;
export const PLAYBACK_HDCP_FAILED = 4012;

// this is not any player error code we are creating this for max device register limit reached error
export const PLAYBACK_DEVICE_LIMIT_REACHED_ERROR = 1;

export const PLAYBACK_NO_ENTITLEMENT = 8001;
export const PLAYBACK_LOCATION_RESTRICTION = 8002;
export const PLAYBACK_STREAM_COULD_EXCEEEDED = 8003;
export const PLAYBACK_PLAY_COUNT_EXCEEDED = 8004;
export const PLAYBACK_DOWNLOAD_COUNT_EXCEEDED = 8005;
export const PLAYBACK_UNSUPPORTED_DEVICE = 8006;
export const PLAYBACK_INVALID_ENTITLEMENT = 8007;
export const PLAYBACK_INVALID_HEARTBEAT = 8008;
export const PLAYBACK_FILES_NOT_AVAILABLE = 8009;
export const PLAYBACK_INVALID_HEARTBEAT_FREQUENCY = 8010;
export const PLAYBACK_INVALID_DELIVERY_TYPE = 8011;
export const PLAYBACK_RATING_RESTRICTION = 8012;
export const PLAYBACK_FILES_FAILED_TO_FETCH = 1002;
export const PLAYBACK_REQUEST_FILTER_ERROR = 1006;
export const PLAYBACK_CONTENT_UNSUPPORTED_BY_BROWSER = 4032;
export const PLAYBACK_CONTENT_NO_PLAY_SOURCE = 7002;

// Authentication errors
export const AUTHENTICATION_UNSPECIFIED = 0;
export const AUTHENTICATION_ACCESS_TOKEN_REQUIRED = 1;
export const AUTHENTICATION_INVALID_ACCESS_TOKEN = 2;
export const AUTHENTICATION_ACCOUNT_REFRESH_TOKEN = 3;
export const AUTHENTICATION_INVALID_CREDENTIALS = 4;
export const AUTHENTICATION_INVALID_ACTIVATION_LINK = 5;

export const SOCIAL_SIGN_IN_UNKNOWN = 0;
export const SOCIAL_SIGN_IN_REQUIRES_LINKING = 1;
export const SOCIAL_SIGN_IN_INVALID_PROVIDER_TOKEN = 2;
export const SOCIAL_SIGN_IN_SOCIAL_IDENTITY_CONFLICT = 3;

export const SERVER_5000_ERROR_RANGE_START = 5001;
export const SERVER_5000_ERROR_RANGE_END = 5009;

export const FORBIDDEN_ERROR = 403;
export const UNAUTHORIZED_ERROR = 401;

export const OTP_FAILED_TO_VERIFY = 7;
export const OTP_EXPIRED = 8;

export const INVALID_PASSWORD = 3;
export const WRONG_USERNAME_PASSWORD = 4;
export const INVALID_PIN = 5;

export const INVALID_ACCESS_TOKEN = 2;
export const INVALID_USER_CHANGED_PASSWORD = 21;
export const INVALID_USER_ACCOUNT_DELETED = 10;

export function mapServiceErrorCodeToVideoErrorCode(serviceErrorCode: number): VideoErrorCode {
	switch (serviceErrorCode) {
		case PLAYBACK_LOCATION_RESTRICTION:
			return VideoErrorCode.GeoBlockedError;
		default:
			return VideoErrorCode.ServerError;
	}
}
